-- +goose Up
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE IF NOT EXISTS actions (
	id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
	name VARCHAR(255) NOT NULL DEFAULT '',
	project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE ON UPDATE CASCADE,
	action VARCHAR(32) NOT NULL,
	data JSONB NOT NULL DEFAULT '{}',
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
	id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
	element_id UUID NOT NULL REFERENCES elements(id) ON DELETE CASCADE ON UPDATE CASCADE,
	action_id UUID NOT NULL REFERENCES actions(id) ON DELETE CASCADE ON UPDATE CASCADE,
	event VARCHAR(32) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE elements DROP IF EXISTS events;

-- +goose Down
-- SQL section 'Down' is executed when this migration is rolled back
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS actions;

ALTER TABLE elements ADD events JSONB NOT NULL DEFAULT '[]';
UPDATE elements SET events = '[]' WHERE events IS NULL;
